import React from 'react';
import DefaultTags from '../components/head/DefaultTags';

function Head() {
  return (
    <>
      <DefaultTags />
      <title>Next.js 13 | Homepage</title>
      <meta name="description" content="Generated by creacte next app" />
    </>
  );
}

export default Head;
